import { useReducer } from "react";
import ExpenseDataContext from "./expenseData--context";
import { v4 as uuidv4 } from "uuid";

const EXPENSE_CATEGORY = {
  food: ["breakfast", "brunch", "lunch", "dinner", "snack", "drink"],
  clothing: ["clothes", "pants", "shoes", "accessories", "underwear"],
  housing: [
    "rent",
    "water  bill",
    "electricity bill",
    "gas bill",
    "cable bill",
    "internet bill",
  ],
  transportation: ["gasoline", "parking", "maintenance"],
  education: ["books", "course"],
  entertainment: ["video games", "computer games", "party"],
  others: ["others"],
};

const INCOME_CATEGORY = {
  salary: ["salary", "bonus"],
  investment: ["stock"],
  others: ["others"],
};

// let originalObj;
const EXPENSE_DATA = [
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2021-08-05",
    year: "2021",
    month: "08",
    day: "05",
    description: "Burger",
    price: "50",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2021-09-05",
    year: "2021",
    month: "09",
    day: "05",
    description: "Burger",
    price: "50",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2021-09-01",
    year: "2021",
    month: "09",
    day: "01",
    description: "Burger",
    price: "50",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "clothing",
    subCate: "t-shirt",
    time: "2021-09-02",
    year: "2021",
    month: "09",
    day: "02",
    description: "Nike",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "bill",
    time: "2021-09-03",
    year: "2021",
    month: "09",
    day: "03",
    description: "June Bill",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "transportation",
    subCate: "bus",
    time: "2021-09-04",
    year: "2021",
    month: "09",
    day: "04",
    description: "bus",
    price: "10",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "salary",
    time: "2021-09-05",
    year: "2021",
    month: "09",
    day: "05",
    description: "salary",
    price: "3000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "bill",
    time: "2021-09-08",
    year: "2021",
    month: "09",
    day: "08",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-09-01",
    year: "2021",
    month: "09",
    day: "01",
    description: "Burger",
    price: "110",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-09-04",
    year: "2021",
    month: "09",
    day: "04",
    description: "AMZN",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "book",
    time: "2021-09-06",
    year: "2021",
    month: "09",
    day: "06",
    description: "",
    price: "50",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "salary",
    time: "2021-09-06",
    year: "2021",
    month: "09",
    day: "06",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "entertainment",
    subCate: "video games",
    time: "2021-09-06",
    year: "2021",
    month: "09",
    day: "06",
    description: "Burger",
    price: "110",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "bonus",
    subCate: "bonus",
    time: "2021-09-06",
    year: "2021",
    month: "09",
    day: "06",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "BreakFast",
    time: "2021-09-06",
    year: "2021",
    month: "09",
    day: "06",
    description: "Burger",
    price: "110",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "others",
    subCate: "others",
    time: "2021-09-07",
    year: "2021",
    month: "09",
    day: "07",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-09-08",
    year: "2021",
    month: "09",
    day: "08",
    description: "",
    price: "190",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "dinner",
    time: "2021-09-08",
    year: "2021",
    month: "09",
    day: "08",
    description: "",
    price: "190",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "books",
    time: "2021-09-08",
    year: "2021",
    month: "09",
    day: "08",
    description: "",
    price: "19",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "entertainment",
    subCate: "party",
    time: "2021-09-09",
    year: "2021",
    month: "09",
    day: "09",
    description: "",
    price: "1578",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "party",
    time: "2021-09-09",
    year: "2021",
    month: "09",
    day: "09",
    description: "",
    price: "3008",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "drink",
    time: "2021-09-10",
    year: "2021",
    month: "09",
    day: "10",
    description: "",
    price: "10",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "clothing",
    subCate: "pants",
    time: "2021-09-11",
    year: "2021",
    month: "09",
    day: "11",
    description: "",
    price: "2500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "clothing",
    subCate: "shoes",
    time: "2021-09-11",
    year: "2021",
    month: "09",
    day: "11",
    description: "",
    price: "1200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "gas bill",
    time: "2021-09-12",
    year: "2021",
    month: "09",
    day: "12",
    description: "",
    price: "1500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "books",
    time: "2021-09-13",
    year: "2021",
    month: "09",
    day: "13",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "entertainment",
    subCate: "video games",
    time: "2021-09-14",
    year: "2021",
    month: "09",
    day: "14",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-09-15",
    year: "2021",
    month: "09",
    day: "15",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2021-09-15",
    year: "2021",
    month: "09",
    day: "15",
    description: "aaaeiwmdwioedmwoemwemdw",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2021-09-15",
    year: "2021",
    month: "09",
    day: "15",
    description: "aaaeiwmdwioedmwoedm",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "books",
    time: "2021-09-15",
    year: "2021",
    month: "09",
    day: "15",
    description: "aaaeiwmdwi",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-09-16",
    year: "2021",
    month: "09",
    day: "16",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-09-17",
    year: "2021",
    month: "09",
    day: "17",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-09-18",
    description: "",
    year: "2021",
    month: "09",
    day: "18",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-09-19",
    year: "2021",
    month: "09",
    day: "19",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-09-20",
    year: "2021",
    month: "09",
    day: "20",
    description: "",
    price: "400",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-09-21",
    year: "2021",
    month: "09",
    day: "21",
    description: "",
    price: "50",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-09-22",
    year: "2021",
    month: "09",
    day: "22",
    description: "",
    price: "450",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-09-23",
    year: "2021",
    month: "09",
    day: "23",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-09-24",
    year: "2021",
    month: "09",
    day: "24",
    description: "",
    price: "800",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2021-09-25",
    year: "2021",
    month: "09",
    day: "25",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "salary",
    time: "2021-09-25",
    year: "2021",
    month: "09",
    day: "25",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "salary",
    time: "2021-09-26",
    year: "2021",
    month: "09",
    day: "26",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-09-27",
    year: "2021",
    month: "09",
    day: "27",
    description: "",
    price: "1200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-09-28",
    year: "2021",
    month: "09",
    day: "28",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-09-29",
    year: "2021",
    month: "09",
    day: "29",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-09-30",
    year: "2021",
    month: "09",
    day: "30",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-09-30",
    year: "2021",
    month: "09",
    day: "30",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2021-10-01",
    year: "2021",
    month: "10",
    day: "01",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-10-01",
    year: "2021",
    month: "10",
    day: "01",
    description: "",
    price: "2000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "clothing",
    subCate: "accessories",
    time: "2021-10-02",
    year: "2021",
    month: "10",
    day: "02",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-10-02",
    year: "2021",
    month: "10",
    day: "02",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "course",
    time: "2021-10-03",
    year: "2021",
    month: "10",
    day: "03",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "course",
    time: "2021-10-04",
    year: "2021",
    month: "10",
    day: "04",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "snack",
    time: "2021-10-05",
    year: "2021",
    month: "10",
    day: "05",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "snack",
    time: "2021-10-05",
    year: "2021",
    month: "10",
    day: "05",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "snack",
    time: "2021-10-11",
    year: "2021",
    month: "10",
    day: "11",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "snack",
    time: "2021-10-15",
    year: "2021",
    month: "10",
    day: "15",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "snack",
    time: "2021-10-20",
    year: "2021",
    month: "10",
    day: "20",
    description: "",
    price: "1200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "snack",
    time: "2021-10-25",
    year: "2021",
    month: "10",
    day: "25",
    description: "",
    price: "130",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-10-26",
    year: "2021",
    month: "10",
    day: "26",
    description: "",
    price: "530",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-10-27",
    year: "2021",
    month: "10",
    day: "27",
    description: "",
    price: "530",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-10-28",
    year: "2021",
    month: "10",
    day: "28",
    description: "",
    price: "530",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-10-29",
    year: "2021",
    month: "10",
    day: "29",
    description: "",
    price: "530",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "transportation",
    subCate: "maintenance",
    time: "2021-10-31",
    year: "2021",
    month: "10",
    day: "31",
    description: "",
    price: "5000",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-11-01",
    year: "2021",
    month: "11",
    day: "01",
    description: "",
    price: "530",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-11-03",
    year: "2021",
    month: "11",
    day: "03",
    description: "",
    price: "530",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-11-05",
    year: "2021",
    month: "11",
    day: "05",
    description: "",
    price: "530",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "electricity bill",
    time: "2021-11-07",
    year: "2021",
    month: "11",
    day: "07",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "electricity bill",
    time: "2021-11-11",
    year: "2021",
    month: "11",
    day: "11",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "electricity bill",
    time: "2021-11-12",
    year: "2021",
    month: "11",
    day: "12",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "electricity bill",
    time: "2021-11-15",
    year: "2021",
    month: "11",
    day: "15",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "brunch",
    time: "2021-11-17",
    year: "2021",
    month: "11",
    day: "17",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "brunch",
    time: "2021-11-20",
    year: "2021",
    month: "11",
    day: "20",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "brunch",
    time: "2021-11-21",
    year: "2021",
    month: "11",
    day: "21",
    description: "",
    price: "50",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "brunch",
    time: "2021-11-25",
    year: "2021",
    month: "11",
    day: "25",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-11-28",
    year: "2021",
    month: "11",
    day: "28",
    description: "",
    price: "600",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-11-28",
    year: "2021",
    month: "11",
    day: "28",
    description: "",
    price: "600",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-11-28",
    year: "2021",
    month: "11",
    day: "28",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "brunch",
    time: "2021-11-28",
    year: "2021",
    month: "11",
    day: "28",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-11-29",
    year: "2021",
    month: "11",
    day: "29",
    description: "",
    price: "900",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2021-11-30",
    year: "2021",
    month: "11",
    day: "30",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "entertainment",
    subCate: "party",
    time: "2021-12-01",
    year: "2021",
    month: "12",
    day: "01",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-02",
    year: "2021",
    month: "12",
    day: "02",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-05",
    year: "2021",
    month: "12",
    day: "05",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-08",
    year: "2021",
    month: "12",
    day: "08",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-10",
    year: "2021",
    month: "12",
    day: "10",
    description: "",
    price: "400",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-11",
    year: "2021",
    month: "12",
    day: "11",
    description: "",
    price: "900",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-13",
    year: "2021",
    month: "12",
    day: "13",
    description: "",
    price: "240",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-15",
    year: "2021",
    month: "12",
    day: "15",
    description: "",
    price: "800",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-18",
    year: "2021",
    month: "12",
    day: "18",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-19",
    year: "2021",
    month: "12",
    day: "19",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2021-12-21",
    year: "2021",
    month: "12",
    day: "21",
    description: "",
    price: "240",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-22",
    year: "2021",
    month: "12",
    day: "22",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-24",
    year: "2021",
    month: "12",
    day: "24",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-25",
    year: "2021",
    month: "12",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-25",
    year: "2021",
    month: "12",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-25",
    year: "2021",
    month: "12",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-25",
    year: "2021",
    month: "12",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-25",
    year: "2021",
    month: "12",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-25",
    year: "2021",
    month: "12",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-25",
    year: "2021",
    month: "12",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-25",
    year: "2021",
    month: "12",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-28",
    year: "2021",
    month: "12",
    day: "28",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2021-12-29",
    year: "2021",
    month: "12",
    day: "29",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2022-01-01",
    year: "2022",
    month: "01",
    day: "01",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2022-01-01",
    year: "2022",
    month: "01",
    day: "01",
    description: "",
    price: "20000",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2022-01-02",
    year: "2022",
    month: "01",
    day: "02",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2022-01-03",
    year: "2022",
    month: "01",
    day: "03",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2022-01-05",
    year: "2022",
    month: "01",
    day: "05",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "bonus",
    time: "2022-01-10",
    year: "2022",
    month: "01",
    day: "10",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-11",
    year: "2022",
    month: "01",
    day: "11",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-13",
    year: "2022",
    month: "01",
    day: "13",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-15",
    year: "2022",
    month: "01",
    day: "15",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-18",
    year: "2022",
    month: "01",
    day: "18",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-20",
    year: "2022",
    month: "01",
    day: "20",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-21",
    year: "2022",
    month: "01",
    day: "21",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-23",
    year: "2022",
    month: "01",
    day: "23",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-24",
    year: "2022",
    month: "01",
    day: "24",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2022-01-24",
    year: "2022",
    month: "01",
    day: "24",
    description: "burger yummy",
    price: "150",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "others",
    time: "2022-01-24",
    year: "2022",
    month: "01",
    day: "24",
    description: "thanks",
    price: "3000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "clothing",
    subCate: "panths",
    time: "2022-01-24",
    year: "2022",
    month: "01",
    day: "24",
    description: "nice looking",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "transportation",
    subCate: "parking",
    time: "2022-01-24",
    year: "2022",
    month: "01",
    day: "24",
    description: "",
    price: "10",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "books",
    time: "2022-01-24",
    year: "2022",
    month: "01",
    day: "24",
    description: "cooding books",
    price: "80",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2022-01-24",
    year: "2022",
    month: "01",
    day: "24",
    description: "ddddddddddddddddddddddddddddddddddddddddddddd",
    price: "150",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-01-25",
    year: "2022",
    month: "01",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-02-04",
    year: "2022",
    month: "02",
    day: "04",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2022-02-01",
    year: "2022",
    month: "02",
    day: "01",
    description: "Burger",
    price: "110",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2022-02-04",
    year: "2022",
    month: "02",
    day: "04",
    description: "AMZN",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "book",
    time: "2022-02-06",
    year: "2022",
    month: "02",
    day: "06",
    description: "",
    price: "50",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "salary",
    time: "2022-02-06",
    year: "2022",
    month: "02",
    day: "06",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "entertainment",
    subCate: "video games",
    time: "2022-02-06",
    year: "2022",
    month: "02",
    day: "06",
    description: "Burger",
    price: "110",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "bonus",
    subCate: "bonus",
    time: "2022-02-06",
    year: "2022",
    month: "02",
    day: "06",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "BreakFast",
    time: "2022-02-06",
    year: "2022",
    month: "02",
    day: "06",
    description: "Burger",
    price: "110",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "others",
    subCate: "others",
    time: "2022-02-07",
    year: "2022",
    month: "02",
    day: "07",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2022-02-08",
    year: "2022",
    month: "02",
    day: "08",
    description: "",
    price: "190",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "dinner",
    time: "2022-02-08",
    year: "2022",
    month: "02",
    day: "08",
    description: "",
    price: "190",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "books",
    time: "2022-02-08",
    year: "2022",
    month: "02",
    day: "08",
    description: "",
    price: "19",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "entertainment",
    subCate: "party",
    time: "2022-02-09",
    year: "2022",
    month: "02",
    day: "09",
    description: "",
    price: "1578",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "party",
    time: "2022-02-09",
    year: "2022",
    month: "02",
    day: "09",
    description: "",
    price: "3008",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "drink",
    time: "2022-02-10",
    year: "2022",
    month: "02",
    day: "10",
    description: "",
    price: "10",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "clothing",
    subCate: "pants",
    time: "2022-02-11",
    year: "2022",
    month: "02",
    day: "11",
    description: "",
    price: "2500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "clothing",
    subCate: "shoes",
    time: "2022-02-11",
    year: "2022",
    month: "02",
    day: "11",
    description: "",
    price: "1200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "housing",
    subCate: "gas bill",
    time: "2022-02-12",
    year: "2022",
    month: "02",
    day: "12",
    description: "",
    price: "1500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "books",
    time: "2022-02-13",
    year: "2022",
    month: "02",
    day: "13",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "entertainment",
    subCate: "video games",
    time: "2022-02-14",
    year: "2022",
    month: "02",
    day: "14",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2022-02-15",
    year: "2022",
    month: "02",
    day: "15",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2022-02-15",
    year: "2022",
    month: "02",
    day: "15",
    description: "aaaeiwmdwioedmwoemwemdw",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2022-02-15",
    year: "2022",
    month: "02",
    day: "15",
    description: "aaaeiwmdwioedmwoedm",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "education",
    subCate: "books",
    time: "2022-02-15",
    year: "2022",
    month: "02",
    day: "15",
    description: "aaaeiwmdwi",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2022-02-16",
    year: "2022",
    month: "02",
    day: "16",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "stock",
    subCate: "stock",
    time: "2022-02-17",
    year: "2022",
    month: "02",
    day: "17",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2022-02-18",
    description: "",
    year: "2022",
    month: "02",
    day: "18",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2022-02-19",
    year: "2022",
    month: "02",
    day: "19",
    description: "",
    price: "100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2022-02-20",
    year: "2022",
    month: "02",
    day: "20",
    description: "",
    price: "400",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2022-02-21",
    year: "2022",
    month: "02",
    day: "21",
    description: "",
    price: "50",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2022-02-22",
    year: "2022",
    month: "02",
    day: "22",
    description: "",
    price: "450",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2022-02-23",
    year: "2022",
    month: "02",
    day: "23",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "lunch",
    time: "2022-02-24",
    year: "2022",
    month: "02",
    day: "24",
    description: "",
    price: "800",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "breakfast",
    time: "2022-02-25",
    year: "2022",
    month: "02",
    day: "25",
    description: "",
    price: "200",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "salary",
    time: "2022-02-25",
    year: "2022",
    month: "02",
    day: "25",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "income",
    mainCate: "salary",
    subCate: "salary",
    time: "2022-02-26",
    year: "2022",
    month: "02",
    day: "26",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2022-02-27",
    year: "2022",
    month: "02",
    day: "27",
    description: "",
    price: "1200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2022-02-28",
    year: "2022",
    month: "02",
    day: "28",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "dinner",
    time: "2022-02-29",
    year: "2022",
    month: "02",
    day: "29",
    description: "",
    price: "100",
  },

  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-03-25",
    year: "2022",
    month: "03",
    day: "25",
    description: "",
    price: "300",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-04-25",
    year: "2022",
    month: "04",
    day: "25",
    description: "",
    price: "1000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-05-25",
    year: "2022",
    month: "05",
    day: "25",
    description: "",
    price: "500",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-06-25",
    year: "2022",
    month: "06",
    day: "25",
    description: "",
    price: "3400",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-07-25",
    year: "2022",
    month: "07",
    day: "25",
    description: "",
    price: "3100",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-08-25",
    year: "2022",
    month: "08",
    day: "25",
    description: "",
    price: "4000",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-09-25",
    year: "2022",
    month: "09",
    day: "25",
    description: "",
    price: "1200",
  },
  {
    id: uuidv4(),
    category: "expense",
    mainCate: "food",
    subCate: "shoes",
    time: "2022-10-25",
    year: "2022",
    month: "10",
    day: "25",
    description: "",
    price: "3400",
  },
];

const reducerInitialObj = {
  expenseData: EXPENSE_DATA,
  expenseDataSearchList: [...EXPENSE_DATA],
  constraintObj: {},
};

function reducer(state, action) {
  switch (action.type) {
    case "DELETE": {
      const expenseData = state.expenseData.filter(
        (element) => element.id !== action.id
      );

      return { ...state, expenseData };
    }

    case "ADD": {
      const expenseData = state.expenseData.concat(action.value);
      return { ...state, expenseData };
    }

    // delete all data in the target category
    case "DELETE_CATEGORY": {
      let expenseData;
      if (action.deleteMainOrSub === "main")
        expenseData = state.expenseData.filter(
          (element) => element.mainCate !== action.value
        );
      else
        expenseData = state.expenseData.filter(
          (element) => element.subCate !== action.value
        );

      return { ...state, expenseData };
    }

    case "EDIT": {
      /*
      actione.value is new edited object
      1) use id to find the date user wanna edit
      2) loop through this data, and edit each new property
      */
      const [editingExpenseData] = state.expenseData.filter(
        (element) => element.id === action.value.id
      );

      for (const key of Object.keys(editingExpenseData)) {
        editingExpenseData[key] = action.value[key];
      }

      return { ...state };
    }

    default:
      return state;
  }
}

function ExpenseDataProvider(props) {
  const [expenseDataState, expenseDataDispatch] = useReducer(
    reducer,
    reducerInitialObj
  );
  // originalObj = expenseDataState.expenseDataSearchList;

  function removeExpenseData(id) {
    expenseDataDispatch({ type: "DELETE", id });
  }

  function addExpenseData(value) {
    expenseDataDispatch({ type: "ADD", value });
  }

  function editExpenseData(value) {
    expenseDataDispatch({ type: "EDIT", value });
  }

  function removeExpenseDataByCategory(deleteMainOrSub, value) {
    expenseDataDispatch({ type: "DELETE_CATEGORY", deleteMainOrSub, value });
  }

  const contextInitialObj = {
    expenseData: expenseDataState.expenseData,
    categoryExpense: EXPENSE_CATEGORY,
    categoryIncome: INCOME_CATEGORY,
    removeExpenseData,
    addExpenseData,
    editExpenseData,
    removeExpenseDataByCategory,
  };

  return (
    <ExpenseDataContext.Provider value={contextInitialObj}>
      {props.children}
    </ExpenseDataContext.Provider>
  );
}

export default ExpenseDataProvider;
